apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: frontend
      template:
        metadata:
          labels:
            app: frontend
        spec:
          containers:
          - image: registry.ocp4.example.com:8443/redhattraining/famous-quotes:latest
            name: famous-quotes
            env:
            - name: QUOTES_USER
              value: operator1
            - name: QUOTES_PASSWORD
              value: redhat123
            - name: QUOTES_DATABASE
              value: quotes
            - name: QUOTES_HOSTNAME
              value: quotesdb
            # readinessProbe:
            #   failureThreshold: 3
            #   initialDelaySeconds: 3
            #   httpGet:
            #     path: /
            #     port: 8000
            #     scheme: HTTP

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      ports:
      - port: 8000
        protocol: TCP
        targetPort: 8000
      selector:
        app: frontend

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      port:
        targetPort: 8000
      to:
        kind: Service
        name: frontend
