apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/redhattraining/php-ssl:latest
        name: php-ssl
        command:
        - sleep
        - 365d
