apiVersion: v1
kind: Pod
metadata:
  name: long-load
spec:
  containers:
  - image: registry.ocp4.example.com:8443/redhattraining/long-load:v1
    imagePullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
    name: long-load
    env:
      - name: START_DELAY
        value: "60000"
  restartPolicy: Always
